### ISSUE TITLE
Blocking the "new" Shorts

### ISSUE THREAD

**Issue by gschmidl** [Onsotumenh/YouTube-Cosmetic-Filters-for-uBlock-Origin#1]
I don't understand why, but the recent change in Shorts (may not be visible for all users yet) seems to only be blockable with

`youtube.com###contents > .ytd-item-section-renderer.style-scope:has(span:has-text(SHORTS))`

why `/Shorts/i` doesn't work is a mystery to me.

**Comment by Onsotumenh** [comment]
Thanks for the information. I've just checked and so far it still works for me. I'll add this version for now and keep an eye open. Redundancy is always a good idea.
