### ISSUE TITLE
Doesn't block "New For You" from search results

### ISSUE THREAD

**Issue by 2dvoid** [Onsotumenh/YouTube-Cosmetic-Filters-for-uBlock-Origin#2]
Not blocking "New for you" section from search results.
![Screenshot from 2022-05-31 10-26-25](https://user-images.githubusercontent.com/65068418/171094042-a5155977-296a-4913-a33b-b88373843177.png)

**Comment by Onsotumenh** [comment]
I haven't encountered that one yet and couldn't reproduce your search either. I've added it to the list for now in hopes it works anyway. If it does (or not) please tell me.

**Comment by 2dvoid** [comment]
Ok, My bad. Everything seems fine after clearing cache of the browser.
