### ISSUE TITLE
Found a line of code that blocks some videos from showing in results

### ISSUE THREAD

**Issue by Sheebalyx** [Onsotumenh/YouTube-Cosmetic-Filters-for-uBlock-Origin#5]
![Screenshot 2024-05-26 011930](https://github.com/Onsotumenh/YouTube-Cosmetic-Filters-for-uBlock-Origin/assets/170852520/fb462ced-83de-4645-96a8-fbd8a2d8e179)

it seems to be specifically the line of code at the bottom of this block

**Comment by Onsotumenh** [comment]
Yeah, that is intentional. I had unmarked shorts popping up, making a time based filter necessary. The last line nukes everything below 2 minutes.

**Comment by Sheebalyx** [comment]
aahhhh I see, that's understandable honestly. The problem being that a lot of videos that aren't actually shorts get blocked too. (primarily music videos and short animations) I will be leaving it out of my filters, definitely your choice on whether or not to change it on the github.

**Comment by Onsotumenh** [comment]
Maybe I'll move it to the optional section and switch it off on my side to see if those unmarked shorts are still popping up (it has been a while and YT is constantly changing).

**Comment by Sheebalyx** [comment]
sounds like a good idea. Also if I remember correctly, shorts have a maximum length of one minute, so you could probably reduce the time minimum regardless.

**Comment by Onsotumenh** [comment]
I had it set to a minute at first but it didn't catch those unmarked ones. My guess is that those didn't get tagged as shorts because they were above one minute and/or YT was experimenting with different duration limits at the time.

The lists are updated. Gonna close this issue now. Have a nice sunday! :)
