### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by bencuri** [Onsotumenh/YouTube-Cosmetic-Filters-for-uBlock-Origin#6]
Sorry for bringing it up here, but I found no other ways to contact you: your Youtube filters are very useful. Would it be possible to do something like this with the Facebook Feed and some other processes of Facebook?

**Comment by Onsotumenh** [comment]
No problem! 

I guess it should be, but I'm not using Facebook. I have been using Reddit and have been blocking quite a bit of stuff with uBlock there as well (e.g. the "use the app to continue" annoyances on mobile firefox). I'm not really a professional, just an amateur with a passionate hate for distractions ;). My tool is mostly the element picker and a few tricks I saw in other custom filters. 

A quick search for Facebook filter lists brought me to this: https://www.fbpurity.com . Maybe worth a try.
I hope I could help!

**Comment by bencuri** [comment]
Thanks! Meanwhile I also found something on Reddit: https://www.reddit.com/r/uBlockOrigin/wiki/solutions/#wiki_fb_feed_inserts

Along with yours this will help a lot. Thank you very much for your useful work and sharing your filter! It will make my life so much better in this nonsense situation Youtube puts users into.
